type Song {
	id: ID!
	name: String
	artist: Artist!
	album: String
	publisher: String
	publicationYear: Int
	genere: String
	views: Int
	words: String
}

type SongQueries {
	topSongs: [Song]
	allSongs: [Song]
	song(id: ID): Song
	search(name: String, album: String, publicationYear: Int): [Song]
}

type SongMutations {
	createSong(input: SongInput): Song
	removeSong(id: ID!): Song
	updateSong(id: ID!, input: SongInput): Song
	songViewed(id: ID!): Song
}

input SongInput {
	name: String!
	artist: ID
	album: String
	publisher: String
	publicationYear: Int
	genere: String
	views: Int
	words: String
}