# the root queries
type Query {
    userQueries: UserQueries
    songQueries: SongQueries
    artistQueries: ArtistQueries
}

type Mutation {
    userMutations: UserMutations
    songMutations: SongMutations
    artistMutations: ArtistMutations
}